version: '2'
services:
  php_54:
    image: mvstudio/php:5.4
    build:
      context: ./5.4

  php_55:
    image: mvstudio/php:5.5
    build:
      context: ./5.5

  php_56:
    image: mvstudio/php:5.6
    build:
      context: ./5.6

  php_56_alpine:
    image: mvstudio/php:5.6-alpine
    build:
      context: ./5.6-alpine

  php_56_alpine_extra:
    image: mvstudio/php:5.6-alpine-extra
    build:
      context: ./5.6-alpine-extra
