name: "CI Github Actions: build"

on: [push]

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build php:7-alpine
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./7-alpine
          file: ./7-alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mvstudio/php:7-alpine

      - name: Build php:8-alpine
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./8-alpine
          file: ./8-alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mvstudio/php:8-alpine
